### ISSUE TITLE
Cannot add new journal

### ISSUE THREAD

**Issue by oliver-pham** [Andrewnt219/mental-health-hacks-journal#31]
Although the user interface indicated a successful operation, I got this error message when creating a new journal.

![Screen Shot 2021-09-11 at 1 26 39 PM](https://user-images.githubusercontent.com/55090719/132956133-2871d63b-cb00-465c-b657-25854d70bbf7.jpg)

**Comment by tuanthanh2067** [comment]
There must be an error with the backend code. Let me take a look

**Comment by tuanthanh2067** [comment]
Turns out, we're out of credits to use firebase functions.

**Comment by oliver-pham** [comment]
Ok then I think it's fine close this issue for now.
